// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eilijuivdrxjjjwjaabx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpbGlqdWl2ZHJ4ampqd2phYWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzcxMTYsImV4cCI6MjA3MDE1MzExNn0.aZLdJSkrLWxmQ51tTJB43D-v8cbhMQu9eRfSeGoNDZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});